version: '3.8'

services:
  doctor-avatar:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./portraits:/app/portraits
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - DEVICE=cuda
      - HOST=0.0.0.0
      - PORT=8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
